export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const GET_STARTUP = "GET_STARTUP";
export const STARTUP_ERROR = "STARTUP_ERROR";
export const LOGOUT = "LOGOUT";
export const CLEAR_STARTUP = "CLEAR_STARTUP";
export const ADD_STARTUP = "ADD_STARTUP";
export const LOAD_STARTUPS = "LOAD_STARTUPS";
export const ADMIN_ERROR_STARTUP = 'ADMIN_ERROR_STARTUP'
export const CLEAR_STARTUPS = "CLEAR_STARTUPS";
export const CLEAN_ALERT = "CLEAN_ALERT"


